name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 18 ]
    
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v3